shrew: Changed config.ac to use TOMCAT_DIR instead of CATALINE_HOME. In oreder to make Tomcat work with configure.ac in a sensible manner I had to have the make target "depends-install" rerun configure so that Tomcat gets detected. Improved OLFS production rules to use TOMCAT_DIR for installation.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -64,22 +64,29 @@ olfs-compile:
 	cd src/olfs && ant $(olfs_version_arg)
 
 olfs-install: check-webapps-privileges olfs-compile
-	if [[ ! -d "$(TOMCAT_DIR)/webapps" ]]; then \
+	@if [[ ! -d "$(TOMCAT_DIR)/webapps" ]]; then \
 		echo "ERROR!! $(TOMCAT_DIR)/webapps is missing."; \
 		echo "ERROR!! There is no place to put the OLFS web application archive! OLFS NOT INSTALLED."; \
 	else \
 		cp src/olfs/build/dist/*.war $(TOMCAT_DIR)/webapps;\
+		echo "OLFS installed to: " $(TOMCAT_DIR)/webapps; \
 	fi
 
-# How do we run the OLFS-specific tests?
+
 olfs-check:
-	./src/olfs/make-check
-	
+	@echo "Checking for Hyrax Service..."
+	@-curl http://localhost:8080/opendap/version;\
+	if [ "$$?" -ne "0" ]; then \
+		echo "ERROR! Hyrax must be running at http://localhost:8080/opendap/ for these tests to work."; \
+	else \
+		echo "Running OLFS Tests."; \
+		cd src/olfs && ./make-check; \
+	fi
 	
 olfs-osx-package:
 	cd src/olfs && ant $(olfs_version_arg) -DCATALINA_HOME=$(TOMCAT_DIR) osx-package
 
-olfs-test:
+showEnv:
 	@echo "prefix: " $(prefix) 
 	@echo "CATALINA_HOME: " $(CATALINA_HOME) 
 	@echo "TOMCAT_DIR: " $(TOMCAT_DIR)
